Server:
  Folder: "C:\\Users\\Giacomo\\Desktop\\minecraft server"
  FileName: "server.jar"
  Protocol: "756"
  Version: "1.17.1"
Commands:
  StartServer: "java <Commands.StartServerParam> -jar <Server.FileName> nogui"
  StartServerParam: "-Xmx1024M -Xms1024M"
  StopServer: "stop"
  StopServerAllowKill: 10
Msh:
  Debug: 1 # [0 - 4]
  InfoHibernation: "                   \u0026fserver status:\n                   \u0026b\u0026lHIBERNATING"
  InfoStarting: "                   \u0026fserver status:\n                    \u00266\u0026lWARMING UP"
  NotifyUpdate: true
  Port: "25555"
  TimeBeforeStoppingEmptyServer: 30
